services:
 traefik:
   networks:
     homelab-gateway-net:
       aliases:
         - dozzle.home.arpa
         - homelab.home.arpa
         - portainer.home.arpa
         - traefik.home.arpa
         - mailpit.home.arpa
         - openvscode.home.arpa
         - gitea.home.arpa
         - nexus.home.arpa
         - jenkins.home.arpa
         - tomcat11.home.arpa
         - neo4j.home.arpa
         - neodash.home.arpa
         - drawio.home.arpa
         - jsonconverter.home.arpa
         - websphere-liberty.home.arpa
         - websphere-liberty-java8.home.arpa
         - wiki.home.arpa
