services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"      
      - "--certificatesresolvers.stepca.acme.caserver=https://step-ca:9000/acme/acme/directory"
      - "--certificatesresolvers.stepca.acme.email=admin@home.arpa"
      - "--certificatesresolvers.stepca.acme.storage=/letsencrypt/stepca-acme.json"
      - "--certificatesresolvers.stepca.acme.httpchallenge=true"
      - "--certificatesresolvers.stepca.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.stepca.acme.cacertificates=/step-ca/certs/root_ca.crt"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../users/homelab.htpasswd:/etc/traefik/.htpasswd:ro
      - traefik_letsencrypt:/letsencrypt
      - step_ca_data:/step-ca:ro
    networks:
      homelab-core-net:
          aliases:
            - dozzle.home.arpa
            - homelab.home.arpa
            - portainer.home.arpa
            - traefik.home.arpa
    depends_on:
      step-ca:
        condition: service_started
    labels:
      - "traefik.enable=true"

      # Traefik Dashboard-Router
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.home.arpa`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-dashboard-redirect"

      # HTTPS router
      - "traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.home.arpa`)"
      - "traefik.http.routers.traefik-dashboard-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard-https.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-https.tls=true"
      - "traefik.http.routers.traefik-dashboard-https.tls.certresolver=stepca"

      # Redirect Middleware
      - "traefik.http.middlewares.traefik-dashboard-redirect.redirectscheme.scheme=https"

volumes:
  traefik_letsencrypt:
    name: traefik_letsencrypt
