services:
  gitea:
    build: .
    container_name: gitea
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000

      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db

      GITEA__security__INSTALL_LOCK: "true"

      GITEA__server__DOMAIN: gitea.home.arpa
      GITEA__server__ROOT_URL: http://gitea.home.arpa/
      GITEA__server__HTTP_PORT: 3000
      GITEA__server__SSH_PORT: 22

      GITEA__service__DISABLE_REGISTRATION: "true"

      # Changes to the credentials have no effect after the first start!
      GITEA_ADMIN_USER: ${GITEA_ADMIN_USER}
      GITEA_ADMIN_PASSWORD: ${GITEA_ADMIN_PASSWORD}
      GITEA_ADMIN_EMAIL: ${GITEA_ADMIN_EMAIL}

      GITEA_DEV_USER: ${GITEA_DEV_USER}
      GITEA_DEV_PASSWORD: ${GITEA_DEV_PASSWORD}
      GITEA_DEV_EMAIL: ${GITEA_DEV_EMAIL}
    volumes:
      - gitea-data:/data
    networks:
      - homelab-devtools-net
      - homelab-gateway-net
    labels:
      - "traefik.enable=true"
      
      - "traefik.docker.network=homelab-gateway-net"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.gitea.rule=Host(`gitea.home.arpa`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.middlewares=gitea-redirect"
      - "traefik.http.routers.gitea.service=gitea"

      # HTTPS router
      - "traefik.http.routers.gitea-https.rule=Host(`gitea.home.arpa`)"
      - "traefik.http.routers.gitea-https.entrypoints=websecure"
      - "traefik.http.routers.gitea-https.tls=true"
      - "traefik.http.routers.gitea-https.tls.certresolver=stepca"
      - "traefik.http.routers.gitea-https.service=gitea"

      # Redirect Middleware
      - "traefik.http.middlewares.gitea-redirect.redirectscheme.scheme=https"

      # Gitea internal port
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  gitea-data:
    name: gitea-data

