name: homelab-devtools

networks:
  homelab-devtools-net:
    driver: bridge
    name: homelab-devtools-net

include:
  - path: ./mailpit/mailpit.yaml
    project_directory: ./mailpit
  - path: ./gitea/gitea.yaml
    project_directory: ./gitea
  - path: ./nexus/nexus.yaml
    project_directory: ./nexus
  - path: ./jenkins/jenkins.yaml
    project_directory: ./jenkins
  - path: ./jenkins-agent-maven/jenkins-agent-maven.yaml
    project_directory: ./jenkins-agent-maven
