services:
  wiki-go:
    image: leomoonstudios/wiki-go
    container_name: wiki-go
    volumes:
      - ./data:/wiki/data:rw
    user: 1000:10
    networks:
      - homelab-core-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki-go.rule=Host(`wiki.nas.local`)"
      - "traefik.http.routers.wiki-go.entrypoints=web"
      - "traefik.http.services.wiki-go.loadbalancer.server.port=8080"
