---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - DXP2800:
        href: http://nas.home.arpa:9999
        description: UGREEN NAS DXP2800
    - Dozzle:
        href: http://dozzle.home.arpa/
        description: Container monitoring
        container: dozzle
    - step-ca:
        href: http://step-ca.home.arpa/
        description: step-ca
        container: step-ca
    - Traefik:
        href: http://traefik.home.arpa/
        description: Reverse proxy
        container: traefik
    - Portainer:
        href: http://portainer.home.arpa/
        description: Container management
        container: portainer
    - Pi-hole:
        href: http://pihole.home.arpa/admin
        description: Pi-hole
        container: pihole

- KnowledgeBase:
    - WikiGo:
        href: http://wiki.nas.local/
        description: Homelab Wiki-Go
        container: wiki-go

- DevTools:
    - OpenVSCode:
        href: https://openvscode.home.arpa/?tkn=dein-langes-token
        description: OpenVSCode-Server
        container: openvscode
    - Gitea:
        href: http://gitea.home.arpa/
        description: Gitea
        container: gitea
    - Jenkins:
        href: http://jenkins.home.arpa/
        description: Jenkins
        container: jenkins
    - Nexus:
        href: http://nexus.home.arpa/
        description: Nexus
        container: nexus
    - Mailpit:
        href: http://mailpit.home.arpa/
        description: Mailpit
        container: mailpit

- Code-Analysis:
    - Neo4J:
        href: http://neo4j.home.arpa/
        description: Neo4J
        container: neo4j
    - NeoDash:
        href: http://neodash.home.arpa/
        description: NeoDash
        container: neodash

- Apps:
    - Tomcat11:
        href: http://tomcat11.home.arpa/
        description: Tomcat11
        container: tomcat11
    - Websphere Liberty - Java8:
        href: https://websphere-liberty-java8.home.arpa/
        description: Websphere Liberty - Java8
        container: websphere-liberty-java8
    - Websphere Liberty - Java8 - AdminCenter:
        href: https://websphere-liberty-java8.home.arpa/adminCenter/
        description: Websphere Liberty - Java8 - AdminCenter
        container: websphere-liberty-java8
