---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - DXP2800:
        href: http://nas.home.arpa:9999
        description: UGREEN NAS DXP2800
    - Dozzle:
        href: http://dozzle.home.arpa/
        description: Container monitoring
        container: core-dozzle-1
    - Traefik:
        href: http://traefik.home.arpa/
        description: Reverse proxy
        container: core-traefik-1
    - Portainer:
        href: http://portainer.home.arpa/
        description: Container management
        container: core-portainer-1
    - Pi-hole:
        href: http://pihole.home.arpa/admin
        description: Pi-hole
        container: pihole-pihole-1

- KnowledgeBase:
    - WikiGo:
        href: http://wiki.nas.local/
        description: Homelab Wiki-Go
        container: core-wiki-go-1

- DevTools:
    - Gitea:
        href: http://gitea.home.arpa/
        description: Gitea
        container: devtools-gitea-1
    - Nexus:
        href: http://nexus.home.arpa/
        description: Nexus
        container: devtools-nexus-1
    - Mailpit:
        href: http://mailpit.home.arpa/
        description: Mailpit
        container: devtools-mailpit-1
