services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "10000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homelab-core-net
    labels:
      - "traefik.enable=true"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.home.arpa`)"
      - "traefik.http.routers.dozzle.entrypoints=web"
      - "traefik.http.routers.dozzle.middlewares=dozzle-redirect"

      # HTTPS router
      - "traefik.http.routers.dozzle-https.rule=Host(`dozzle.home.arpa`)"
      - "traefik.http.routers.dozzle-https.entrypoints=websecure"
      - "traefik.http.routers.dozzle-https.tls=true"
      - "traefik.http.routers.dozzle-https.tls.certresolver=stepca"

      # Redirect Middleware
      - "traefik.http.middlewares.dozzle-redirect.redirectscheme.scheme=https"

      # Traefik internal port
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
