services:
  homelab:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: landing-page
    volumes:
      - ./homepage-config:/app/config
      - ./homepage-backgrounds:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homelab.home.arpa
    networks:
      - homelab-core-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homelab.rule=Host(`homelab.home.arpa`)"
      - "traefik.http.routers.homelab.entrypoints=web"
      - "traefik.http.services.homelab.loadbalancer.server.port=3000"
