services:
  homelab:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: landing-page
    volumes:
      - ./homepage-config:/app/config
      - ./homepage-backgrounds:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homelab.home.arpa
    networks:
      - homelab-core-net
    labels:
      - "traefik.enable=true"
      
      # HTTP -> HTTPS redirect
      - "traefik.http.routers.landing-page.service=landing-page"
      - "traefik.http.routers.landing-page.rule=Host(`homelab.home.arpa`)"
      - "traefik.http.routers.landing-page.entrypoints=web"
      - "traefik.http.routers.landing-page.middlewares=landing-page-redirect"

      # HTTPS router
      - "traefik.http.routers.landing-page-https.service=landing-page"
      - "traefik.http.routers.landing-page-https.rule=Host(`homelab.home.arpa`)"
      - "traefik.http.routers.landing-page-https.entrypoints=websecure"
      - "traefik.http.routers.landing-page-https.tls=true"
      - "traefik.http.routers.landing-page-https.tls.certresolver=stepca"

      # Redirect Middleware
      - "traefik.http.middlewares.landing-page-redirect.redirectscheme.scheme=https"

      # Traefik internal port
      - "traefik.http.services.landing-page.loadbalancer.server.port=3000"
